Add Afrezza, Apidra, Levemir, Basaglar and Tresiba profiles, and correct Lantus, Toujeo and Novo Rapid profiles based on more recent data.
NightscoutFoundation/xDrip pull request #1388
Opened 2020-07-23 20:57 UTC by J141

This pull request will add Afrezza, Apidra, Levemir, Basaglar and Tresiba insulin profiles to Xdrip, and corrects profile data for Lantus, Toujeo and Novo Rapid based on published activity graph data. (Most notably, Lantus was listed as a 36-hour insulin while even the manufacturer published an activity graph showing only 24 hours of activity)

Numerous sources were used to find the profiles for each of these insulins.
[https://dlife.com/insulin-chart/](https://dlife.com/insulin-chart/)
[https://my.clevelandclinic.org/health/drugs/13902-injectable-insulin-medications](https://my.clevelandclinic.org/health/drugs/13902-injectable-insulin-medications)
[https://alliedhealth.ceconnection.com/ovidfiles/01741002-201807000-00005.pdf](https://alliedhealth.ceconnection.com/ovidfiles/01741002-201807000-00005.pdf)
[Activity graph showing profiles for various insulins](https://www.google.com/search?q=insulin+degludec+profile&hl=nl&sxsrf=ALeKk018cw2FKxyf0-CkcArCyY4quxs2zA:1595536132525&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjV256jm-TqAhVG2KQKHfdyBs0Q_AUoAXoECAwQAw&biw=1920&bih=937#imgrc=dUuqMmwmOReLSM)
[https://www.ema.europa.eu/en/documents/variation-report/novorapid-h-c-258-p46-0044-epar-assessment-report_en.pdf](https://www.ema.europa.eu/en/documents/variation-report/novorapid-h-c-258-p46-0044-epar-assessment-report_en.pdf)
[https://www.toujeopro.com/toujeo-vs-lantus-efficacy-safety](https://www.toujeopro.com/toujeo-vs-lantus-efficacy-safety)
[https://www.afrezza.com/pdf/Prescribinginfo.pdf](https://www.afrezza.com/pdf/Prescribinginfo.pdf)

Additionally, because the amount of insulin profiles was increased from 7 to 12, the list of profiles in the _insulinprofile_editor_ activity originally overflowed, causing some profiles to be unselectable:

<img src="https://user-images.githubusercontent.com/28660369/88337124-74d0f200-cd36-11ea-81f3-76e7be4436e1.png" data-canonical-src="https://user-images.githubusercontent.com/28660369/88337124-74d0f200-cd36-11ea-81f3-76e7be4436e1.png" width="200"/>

To fix this, i've wrapped the insulin profiles in a ScrollView for future proofing in case more profiles are added in the future, and i've moved the basal/bolus dropdowns and cancel, reset and save buttons down to create more room for selecting insulins. The result is this:

<img src="https://user-images.githubusercontent.com/28660369/88337717-74852680-cd37-11ea-982d-08e5b1b87a11.png" data-canonical-src="https://user-images.githubusercontent.com/28660369/88337717-74852680-cd37-11ea-982d-08e5b1b87a11.png" width="200"/>

These additions should hopefully make it much easier for users to create profiles that correlate better to their insulin needs, by both making MDI easier to configure and BG predictions more accurate.

2020-07-23 21:38 UTC, ANDREAPIPPI commented
Wow J141, these are very good news.
I hope to see it reviewed and merged in a short time.
Very appreciated, well done!
Bye
Pippo     :-)
--

2020-07-25 07:38 UTC, jamorham commented
@gruoner @stephencmorton can you provide comments on this PR please, thanks

2020-07-25 19:37 UTC, gruoner commented
i will merge the PR to my DEV train and have a test - coming back soon

2020-07-26 00:20 UTC, stephencmorton commented
I didn't look in tremendous detail, but it all looks _reasonable_ to me anyway.

To be honest, at a meta level, I'm less and less convinced that this feature of tracking longer-lasting insulin makes much sense. I was only interested because NPH can be used as either pure-basal, or a basal+"delayed bolus" (e.g. if you don't want your child to have to inject at school, you can delay their lunch bolus by using NPH at home at breakfast time). But a lot of that NPH is still basal, so how do you account for what part is basal and what is bolus? Including all the basal parts in your bolus calculations could throw everything off.

2020-07-26 18:30 UTC, gruoner commented
i had a successful compile and deployment and **everything is running as expected**. BUT someone with smaller display sizes (like me who uses a galaxy star) might get problems with the double sliding screen (first slider because the whole page is larger than the screen and second slider because the insulin scrollview). So it might be better to use fixed size for the bottom part and "the rest" of the available screen size for the scrollview? How can i add this to the PR or is it better J141 would do this?

2020-07-26 20:47 UTC, gruoner commented
@stephencmorton 
i can't really understand your arguments against long acting insulin profiles..... From my point of view insulin activity is reduction of blood glucose - whenever insulin activity will occur it will reduce blood glucose; regardless of ultrafast-, fast-, short- or long-acting profiles. Insulin is insulin and it will reduce blood glucose.
When my point of view is correct, all types of "acting insulin" is just (and only) a matter of therapy, not a matter of prediction.....
So one can use it for predicting effects of FIASP, novorapid and even levemir and Tresiba. BUT the precision and "correctness" of the activity model is much more important for longer acting profiles than for shorter or faster acting ones - that's for sure. And here such effects like accumulation of constant and regularly tresiba injection will get really important to be represented by the insulin activity model. When your arguments are addressing this issue of precision i can agree with you and together we can work on other activity models to increase precision. I'm quite sure there are lots of research papers where we can find information how really long acting profiles effect blood glucose.....

2020-07-26 21:10 UTC, stephencmorton commented
@gruoner Let my try to clarify.

Insulin needs are generally divided into two categories "bolus" insulin which compensates the carbs you eat, and "basal" insulin that serves your body's metabolic needs. These are both important, but different.

We have concepts such as "I:C" ratio and Insulin Sensitivity Factor (ISF, often also referred to as a "correction factor"). 

When a program like xDrip+ calculates your predicted BG based on injected insulin and their corresponding decay profiles,  food ingested and its corresponding decay profile, and your I:C ratio it is usually just talking about "bolus" insulin.

When a program like xDrip+ calculates the correcting effect of taking a certain amount of insulin to treat a high, based on your ISF, again this ISF is generally purely based on "bolus" insulin.

If you simply have a long-acting insulin like Tresiba and you want to put it in xDrip+ and you choose to _not_ have it be part of the insulin calculations, this is fine, it's business as usual.
    If you choose to have your long acting insulin be part of the insulin calculations, it will throw everything off. You could  give it new I:C ratios and ISF values. But those will be non-standard values that will a) not really make sense and b) will confuse your endo because "you're not doing it right".

But things get more confusing with something like NPH because often it's used as part-basal and part-bolus. (You can see how an NPH curve is kind of like a flat basal long-acting insulin curve added to a delayed Humalog curve.) Here, what do you do? Do you make it part of your calculations, or do you not? Neither is really satisfactory.

The only real solution would be to also add a "required basal profile" to xDrip+ as well. For pumpers, it's just what you put in your pump as your basal profile. For those injecting insulin, you'd need some UI to add it. (A very rough solution would be to simply say "I need x Units/hour basal" which is not terribly accurate, but is better than nothing.)

Full disclosure: I haven't used xDrip+ in ages, so my understanding of its operation may be flawed.

If this doesn't convince you, let's not make a long drawn-out discussion, let's just agree to not understand each other. I've had trouble convincing you of anything at all in the past.

2020-07-26 21:51 UTC, ANDREAPIPPI commented
Hi Gruoner and stephencmorton.
I would also like to express my opinion, and here it is: instead of discussing the sex of the angels (because in the end this is the result), why don't you let us check what's the effect in the REAL use of this new approach?
Surely I can say that the current system, with Tresiba's values not given because actually it cannot be done, is NOT precise enough, and sometimes badly wrong, at least for me. 
So why don't we check what is the real importance of using a basal insulin value in the IOB calculation?
Maybe Gruoner is right, or stephencmorton is right, or both or nobody is right, but we will never know it only with words.
So please approve and merge it, and let's see what happens!
In this way you will be able to discuss using "in the field" real data.
My little 2 cents.
Pippo    :-)

2020-07-26 21:52 UTC, gruoner commented
OK; now its getting clear - you are stuck in basal/bolus therapy, but there are lots of other insulin therapies.....
All concepts you are using (basal, bolus, I:C ratio and ISF) are concepts of basal/bolus therapy and this kind of therapy assumes that there is a difference between reducing BG from eating and reducing BG for "metabolic needs". That's OK, but in the end its reduction of BG regardless where it comes from or what it is used for....
I can agree your issues with NPH and any other "multi purpose insulin product" - it can't be calculated in a basal/bolus therapy schema. BUT this isn't a problem of xDrip, it is a problem of your therapy as it can't handle it.
Now lets think about how we might calculate such multi purpose products to get a correct I:C, ISF and even a correct basal rate and lets implement it in xdrip.......

2020-07-26 21:55 UTC, stephencmorton commented
@ANDREAPIPPI  I'm not an xDrip+ developer/maintainer. I'm just a guy who once commented on this feature, and found a few  calculation errors in it. I have no authority to approve anything.

Personally, as a professional SW developer though, I would argue that you test and shake out all the bugs before approving any pull request. (Especially for medical SW which life and death decisions may be based on, but really just on principle for any sw.)

2020-07-26 22:01 UTC, gruoner commented
@ANDREAPIPPI **i totally agree with you**, but @stephencmorton reflected another issue and (as i'm also using a NPH) i think we should discuss how to address it.
i  advice an authorization of this PR and some days after merge and release we can discuss your experience with the new tresiba prediction; i'm really excited.....

2020-07-27 22:24 UTC, gruoner commented
@diabeticTurtle & @cominixo i saw your emoji but a simple thumps down is pretty less for such an important discussion like "how do we want to use multiple insulin profiles in xdrip?"
Can you describe your issues u have with my comment - maybe its a matter of my lousy english?

2020-07-28 04:00 UTC, stephencmorton commented
@gruoner I do not know the reasons behind others' emojis. I admit that I am a newb when it comes to T1D and insulin, so I could be completely wrong. But AFAIK, most treatments are based around basal/bolus therapy. Perhaps they were indicating that anybody implying otherwise, is making pretty outrageous statements. As I said I'm new to this, can you point me to some insulin therapies backed by large diabetic/medical organizations that are not based on basal/bolus concepts?

2020-07-28 04:14 UTC, cominixo commented
The thing is, just because "there are other insulin therapies" doesn't mean they're accessible to everyone, and even then not everyone wants to use a pump and just prefer to stay on MDI. There's no reason to not have as many options as we can.

2020-07-28 07:07 UTC, J141 commented
I'm going to add my two cents here, but isn't xdrip designed to offer as many options to as much people as possible? If so, I say we shouldn't be having a discussion on how we want to do multiple insulins in xdrip but rather allow the user to adjust xdrip's behaviour to their specific therapy and needs. people might be stuck on basal/bolus therapy, but i think that should only be more reason to support that therapy, not exclude it.

I also don't agree with your point that long term insulin is going to reduce BG regardless @gruoner. The point being that in order to correctly predict how a basal insulin affects one's BG, xdrip would somehow have to model the rise in BG levels when someone uses no basal insulin, which xdrip currently doesn't do and which i think is hardly doable because bodies' insulin needs vary troughout the day.

Currently i need 48 units of tresiba a day just to keep a roughly baseline BG level during the daytime. If i'd inject 30 units, my BG level would definitely shoot up as my body's basic insulin needs wouldn't be met. However right now if i'd enter 30 units of Tresiba into xdrip, xdrip is going to predict a rather steep drop in BG where in reality i'm not going to drop at all but rather climb up.

Rather than discuss how the basal predictions should work, i was planning on opening another PR soon to include an option not to use basal insulin in iob calculations, as this would solve a big part of the insulin predictions being unreliable for people on basal/bolus therapy that also want to keep track of their basal insulin, while keeping the current way of prediction open to people who prefer this mode of operation.

2020-07-28 07:29 UTC, gruoner commented
**thats the point** - "large diabetic/medical organizations" always use/prefer therapy schema like basal/bolus as they are "very easy" to calculate WITHOUT any usage of IT - quite everyone can calculate his/her needs for basal insulin and their needs for bolus before/after eating and he/she doesn't even need a calculator. That's a very very (very)*..... big advantage of FIT and any other basal/bolus schema.
BUT (with xdrip and nightscout) we are in another situation - we use (and need) IT to support our T1D therapy; thus we can break with such limiting concepts like "basal for metabolic and bolus for eating needs" and we can harvest the fruits of this outbreak (e.g. limitless usage of multi purpose profiles like NPH and a "better" or "more precise" prediction of BG resulting in "better" therapy treatments)......

And now it comes to the really important question: is (the mainstream) xdrip a good container to evaluate such experiments or should we even establish a new train (of course with light-weighted connections to the mainstream) xdrip because even if we implement "experimental feature switches" and let the user completely switching off this experimental code / experimental ideas, it is even in the package and can effect users (e.g. with pump therapy) which NEVER will be addressed by these experimental ideas.

I ask (and i'm really interested in your thoughts): can we protect other users from the negative effects of this experimental code (and any other belonging to such experimental ideas) enough, to save us from a second xdrip train and let all the other user harvest the fruits of these ideas (as they want to!!) OR do we really need a second (experimental) xdrip train to evaluate such concepts/ideas?

2020-07-28 07:37 UTC, gruoner commented
@J141 
AFAIK there is a switch to exclude basal injection from BG prediction
![Bildschirmfoto vom 2020-07-28 09-36-49](https://user-images.githubusercontent.com/51212163/88633911-f10c6200-d0b5-11ea-906e-e2b7e996abd5.png)

2020-07-28 08:01 UTC, gruoner commented
i've got a question belonging to the need of basal insulin (esp. but not exclusively to @stephencmorton and @J141)
what are the main (in meaning of the most influencing) factors for the need of basal insulin for "metabolic needs"? Of couse it is weight of the person but what else?

2020-07-28 08:25 UTC, J141 commented
@gruoner 

> ... That's a very very (very)*..... big advantage of FIT and any other basal/bolus schema.
> BUT (with xdrip and nightscout) we are in another situation - we use (and need) IT to support our T1D therapy; thus we can break with such limiting concepts like "basal for metabolic and bolus for eating needs" and we can harvest the fruits of this outbreak  ...

I agree with you that xDrip's situation gives a good foundation to break with these traditional concepts, and i'm definitely happy to see various kinds of experimentation being added. _however_, i disagree with your opinion that we should completely break away from the traditional concepts of basal/bolus therapy just because we can experiment with other approaches.

A lot of people i know use xDrip, and all but one of them aren't using xDrip to experiment with approaches at all. They rather use xDrip simply because they want to integrate their FGM/CGM/FGM bluetooth bridge with an app that can continually receive these values, alert them of high/low BG and perhaps even predict where their BG levels are going in advance or upload their data to other systems that xDrip can upload into. 

All of these users use basal/bolus therapy, and none of them would be served well if xDrip was to break away from basal/bolus completely and use different approaches instead. And besides that, a lot of these users wouldn't be savvy enough to understand how certain experimental features work and/or how that's going to affect their predictions. Even with the current options i frequently enough see people asking for help because they have no idea what they're configuring in xDrip's settings.

> And now it comes to the really important question: is (the mainstream) xdrip a good container to evaluate such experiments or should we even establish a new train (of course with light-weighted connections to the mainstream) xdrip because even if we implement "experimental feature switches" and let the user completely switching off this experimental code / experimental ideas, it is even in the package and can effect users (e.g. with pump therapy) which NEVER will be addressed by these experimental ideas.

Because of my opinion above that many people just aren't savvy enough to understand how certain experimental features affect them or what works for them and what doesn't, my opinion is that for the really experimental stuff, where we'd try out new and unconventional approaches, xDrip _needs_ an experimental version of the app and these features _need_ to stay out of the mainstream app until they're well tested, to protect users from themselves. We're working with medical-background software after all, and if users start trusting and relying on badly working experimental features it could lead to very dangerous consequences, which i think is in all of our interest to avoid.

2020-07-28 08:33 UTC, J141 commented
However, i also feel that this discussion about whether experimental features should be included in the mainstreap app or a separate app, and how xDrip should handle basal insulin is going off-track and is missing the original goal of this PR. 

xDrip already has insulin types, and already has onset, peak and duration predictions for insulin types. However currently there are only 5 insulin types included while a lot of people use other insulins. **The goal of this PR is to expand the list of insulins from 5 to 12 to better support the various insulins people may be using with the current set of features in xDrip.** 

How the basal dosage is then used in calculations in xDrip and whether xDrip should continue supporting basal/bolus dosages or not is outside the scope that this PR targets and is definitely not a feature this PR changes or touches at all. 

For discussing on whether xDrip should keep basal/bolus or not and/or how basal should be used in iob calculations, i would like to suggest opening a new PR dedicated to that discussion.

2020-07-28 08:39 UTC, gruoner commented
@J141 understood and agreed!!

2020-08-04 20:31 UTC, munster-shug commented
As a brand new CGM user and a newbie to xdrip+ firstly let me express my huge thanks to all the developers and active contributers on here. Honestly folks, you perhaps cannot understand the sense of control and power that I feel over my body for the first time in over 20 years as t1d. Thank youThank youThank you.
But on this topic I am confused as the xdrip+ android app that I cannot find any options to adjust insulin profiles in the android app version that I have. Should I be seeing a treatment profile or multipleiinsulin page as per @j141 post https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-664832793

2020-08-04 21:00 UTC, J141 commented
Hey @munster-shug,

the multiple insulin feature is currently only available on the nightly builds, and not the latest "official release" apk. The nightlies (which really is a bad name that should've been 'previews') are pretty stable and safe to install though. 

You can grab the latest nightly from this page: https://github.com/NightscoutFoundation/xDrip/releases

However please note that currently only the 7 insulin types as seen in this screenshot are supported:
https://user-images.githubusercontent.com/28660369/88337124-74d0f200-cd36-11ea-81f3-76e7be4436e1.png

the 12 insulin types as seen in my first post aren't available in the official xdrip app yet. A pull request is essentially a request to include some changes to the code in the official app, and the maintainer of xdrip+ @jamorham hasn't made a decision on whether to include this change yet.

If you can't wait and really want to use the app with the additional insulin types i've added, feel free to send me an email at j[dot]dekoning141<at>gmail{dot}com and i'll send you a signed apk that includes this change that you can install on your phone. Note that that would mean using an unofficial version of the app that would not be supported by the maintainers of xdrip+ though.

2020-08-11 23:14 UTC, munster-shug commented
Thanks @j141.  I'll await @jamorham s call on whether or not to include this PR in official version

2020-08-17 07:20 UTC, jamorham commented
I'm happy to include this if we think that the numbers describing the insulin action profiles are likely to be as accurate as they can be. 

When this feature was first introduced I added the ability to exclude basal insulin from the calculations because I don't think it makes sense when there is no modelling at all for metabolic glucose rise that is unrelated at all to food intake. I do think it is important for users to be able to record basal insulin doses though. 

I haven't studied this PR in great detail but as long as it preserves that behavior then I think that should be good. I'm not sure how to handle insulins like NPR which may or may not be considered basal. From memory I think the decision on whether an insulin is basal is based on its action time being more than a specified amount.

2020-08-17 09:17 UTC, J141 commented
Hey @jamorham,
this PR only alters the profiles in insulin_profiles.txt, and alters the insulin editor settings view to provide room for displaying the new profiles. 

I've taken special care not to alter any business logic, so xdrip's current behaviour regarding basal insulin is maintained.

2020-08-17 09:39 UTC, tolot27 commented
It would be nice to separate the basal activity option into two: "plot basal activity on graph" and "incorporate basal activity in predictive model". The second option could raise a warning.

2020-08-17 10:09 UTC, J141 commented
Well, feel free to create a PR with that functionality if you think it's useful. That's outside the scope of this PR though, which aims only to add and alter insulin profiles without touching any business logic.

2020-08-17 10:09 UTC, J141 commented
Well, feel free to create a PR with that functionality if you think it's useful. That's outside the scope of this PR though, which aims only to add and alter insulin profiles without touching any business logic.

2020-10-25 19:33 UTC, natalyaerkina commented
That's brilliant! Is there maybe a fork with this functionality, or could I get an apk for testing? It's really interesting, we are on Levemir and Apidra and the stock Lantus and Novorapid profiles are not really working, even with Novorapid itself, the curve seems pretty wrong, it doesn't represent Novorapid's comparatively slow onset, a very noticeable peak at 2h and quick decay between 2h and 3h. Thank you for your work!

2020-11-07 17:57 UTC, ANDREAPIPPI commented
Hi.
Nobody can approve this merging?
Please.
Andrea  :-)

2020-11-20 15:11 UTC, gapolv commented
Hello guys, before anything, I would like to personally congrats all of you participating on this development. xDrip is an amazing tool.

Talking about different kinds of insulin, they are commonly used for us on MDI when trying to cover different kinds of macronutrients than carbohydrates, I mean, protein and fats in this case. Having this said, it would be interesting to have the protein and fats predicting models, as they don't act like CHO.

As additional comment on the basal discussion, for those on MDI, the basal insulin is supposed (if rightly dosed) to do not interfere with the glucose levels during the day (even if fasting). Personally I'm pretty OK not having it on the graphs and predictions. 

Thanks again for all the support and effort.

Gabriel

2020-11-21 08:43 UTC, gruoner commented
Hi Gabriel

as i'm working on a multi carbs feature (based on the food entities in nightscout server) i need to know how fats and protein are effecting BG over time. Currently i'm just predicting CHO by using GI and GL as evaluated and published by diabetic websites - i know, that's not much precise as it could be, but its the same level of precision as using linear trapezoid curves for insulin profiles.
I think (can't really prove it), all the other food ingredients (like fats and protein and maybe also roughage) are influencing BG much more that a more precise model for CHO.

So: are there any curves or model showing carbs activity for fats and protein published?

2020-11-21 13:48 UTC, ANDREAPIPPI commented
Hi Gruoner.
May be here you'll find something that can help...
https://www.nal.usda.gov/sites/default/files/fnic_uploads/energy_full_report.pdf
Bye.
Andrea     :-)

2020-11-21 17:17 UTC, gruoner commented
Hi Andrea

wow; that’s really comprehensive - will need some weeks to study. But it might be my breakthrough modelling all parts of food.
Now i will start a new issue to get a discussion point for the multi carbs feature.....

thank u very much for sharing u'r knowledge

2020-11-21 18:17 UTC, ANDREAPIPPI commented
Never mind, Gruoner, this is my interest too, so I'm just trying to help for a final result, useful for all.
Take your time to study it, it's a bit complicate, IMO, and I'm not sure it is exactly what you were searching for, so if you need more information/data, I'll try to find them.
Bye.
Andrea   :-)

2020-11-21 20:59 UTC, gapolv commented
> Hi Gabriel
> 
> as i'm working on a multi carbs feature (based on the food entities in nightscout server) i need to know how fats and protein are effecting BG over time. Currently i'm just predicting CHO by using GI and GL as evaluated and published by diabetic websites - i know, that's not much precise as it could be, but its the same level of precision as using linear trapezoid curves for insulin profiles.
> I think (can't really prove it), all the other food ingredients (like fats and protein and maybe also roughage) are influencing BG much more that a more precise model for CHO.
> 
> So: are there any curves or model showing carbs activity for fats and protein published?

Hi gruoner,

Thanks for your attention on this topic.
I can tell you a little bit from personal experience, and then some links with graphic illustration of it.
In case of proten, I normally count from 40% to 60% (higher % if not counting fats) of it "as CHO", the glucose spike occurs between 2h-3h after eating.
For fats, from 30% to 0% of it "as CHO", if fat amount is higher than 30g in the meal, then 30% of it will be considered "as CHO", the glucose spike will happen 4h-6h after meal (higher amounts of fat will generate longer glucose impacts).

Here you go with some material:

1) Text discussion: https://www.waltzingthedragon.ca/diabetes/nutrition-exercise/how-fat-and-protein-affect-blood-glucose/
2) Good graphic, it says insulin, but it's a good representation (fat glucose impact seems high in T1D though): https://www.virtahealth.com/blog/top-keto-mistakes
3) Another visual representation: https://www.tandemdiabetes.com/blog/post/general/2018/01/04/carb-counting-1-food-and-blood-glucose
4) https://wa.kaiserpermanente.org/healthAndWellness/index.jhtml?item=%2Fcommon%2FhealthAndWellness%2Fconditions%2Fdiabetes%2FfoodRates.html
5) https://www.diabetes-support.org.uk/info/?page_id=438

Please let me know if can I support this discussion/development in any other way, I would be glad to participate.

Thanks again,
Gabriel

2020-11-21 21:06 UTC, ANDREAPIPPI commented
1457 / 5000
Risultati della traduzione
Just to stick with pull request # 1388, since nothing is happening at the moment, everyone stays on their own opinion, and so on, I was thinking about the feared danger of making basal insulin insertion available in the calculations, an option not entirely understood and tested, fear which gave rise to the proposal to create an xdrip fork (minimal) that could allow to test the use of basal insulins, including Tresiba, in xdrip calculations of current and expected blood sugar
This too has received mixed opinions, and I am one of the opponents.
Actually xdrip nightly already has an option which is shown as "diagnostic only", and as far as basal insulins are concerned, we have the "Use basal activity" option which can be used freely and which I suppose does something in the glycemic calculations.
But I don't think anyone has had a problem with these options.
So I think it might be safe enough to put all options regarding basal insulin types under "TEST ONLY, don't use if unsure what you're doing", or something
Furthermore xdrip clearly states that "This is a DIY product, you decide for yourself", NOT a medical device, and that it should be used under medical supervision!
So what's the deal with doing what I suggest?
Just my opinion, of course, but I'd like to read others' too, especially Jamorham's.
Hello to all.
Andrea     :-)

2021-02-01 09:39 UTC, ulisse31 commented
I'm new to xDrip+ (installed last week) and exploring its features.
I'm following this PR as it matters me a lot.
I wish to add my two cents to the discussion, especially now since it seems this PR is floating in high waters.
The major concern is adding a new feature in the app, which could result in health issues.
On the other hand, this ultra conservative approach (while welcomed) is negatively impacting a number of users which cannot take advantage of the new feature(s).
The major points to account here are that:
1) this app is not a medical device (and those who do that, they do at their own risk and with consent)
2) there are a multitude of different users and needs, and this app should give as much freedom (options) as possible to the end users so that their needs are fulfilled.

My view is to add the feature in a "disabled" state by default, and/or in an experimental menu. This won't negatively affect current users (nothing will change for them).
On the other hand, other users willing to experiment at their own risk could enable the feature and provide feedback for further refinement.

I strongly believe that this would lead to an overall better product in general.

2021-02-09 05:22 UTC, NobodyYouKnow commented
I know this is not a democracy, but I'd still like to cast my vote for implementing this PR. I use Levemir as my basal insulin, and it would be a measurable improvement to this tool to have it recognized. Thanks for your consideration.

-Pat

2021-02-17 22:45 UTC, Ja1Denis commented
We are using xdrip for a few years back as the first app to control our blood sugar. It's an excellent application and congratulations to everyone who develops and maintain the app.
Adding a Levemir to the app would be a significant step. I know that this app only recommends what could happen with the blood sugar, and we do not blindly trust in the predictions.
So, give a chance to Levemir in multiple insulin types.

2021-02-18 09:11 UTC, SBee76 commented
Hi, so just wanting to throw my 2 cents in, I'm in aggreeance with recent commenters. Adding Levemir plus other insulins that people may use as added insulin profiles, would be extremely helpful for those of us on MDI. If I'm to convince my health professionals that this is an excellent alternative to manufacturer apps, then I need it to show my basal treatments properly, even if only in name. 
From what I can understand from the earlier conversations, the problem is that adding new info like this, could create issues in regards to treatments and calculations? Don't we all live that way anyway? The warning about not using as a diagnostic tool and making treatment decisions based on results or prediction is already there, is it not? 
Anyway, I would really love it if it could be listed in some way so that I don't have to explain to my endo why it says Lantus instead. 

I love the developers work and would absolutely contribute in a more useful fashion, if I knew how!

2021-03-24 12:18 UTC, gporfirio commented
Hi,
How can I test It? I do have to change/add the code by myself? Don't you have the APK file? Sorry If It seems like stupid. I don't have much knowledge on codes.

2021-03-29 06:20 UTC, nightscout-ricsi commented
This would be a great improvement, we use Tresiba and Novorapid. Thanks all the work!

2021-04-14 15:21 UTC, walczakkamil approved these changes

2021-04-14 15:23 UTC, walczakkamil approved these changes
Looks OK.

2021-04-28 14:18 UTC, suside approved these changes
This is ready to merge. 

master + PR branch:
<img src="https://user-images.githubusercontent.com/197044/116417509-9f0e8d80-a83b-11eb-84d8-8031952d8c48.png" width="25%">

2021-04-28 18:54 UTC, tolot27 commented
@suside and @walczakkamil Your approval does not result in merging this PR sooner. We need a critical and careful review of the code and not just "looks" good or "ready to merge".
Or more specific: only core developers should be able to approve PRs. But this is not configured (protected branches), currently.

2021-04-28 19:20 UTC, tolot27 reviewed
> @ANDREAPIPPI I'm not an xDrip+ developer/maintainer. I'm just a guy who once commented on this feature, and found a few calculation errors in it. I have no authority to approve anything.

@stephencmorton Please can you explain the "few calculation errors " you have found?

> Personally, as a professional SW developer though, I would argue that you test and shake out all the bugs before approving any pull request. (Especially for medical SW which life and death decisions may be based on, but really just on principle for any sw.)

What are the most important bugs you'd like to see "shaked out" before merging THIS PR?

2021-04-28 19:38 UTC, suside commented
> @suside and @walczakkamil Your approval does not result in merging this PR sooner. We need a critical and careful review of the code and not just "looks" good or "ready to merge".

The thing is that there is **no code to review here**, only updated insulin list and small gui change, which you can see on screenshots.
And if by _critical and careful review of the code_ you mean basal issues this https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-664859627 of the PR author pretty much sums it up.

2021-04-28 19:42 UTC, suside commented on app/src/main/res/layout/activity_insulinprofile_editor.xml
> +                    android:layout_gravity="bottom"
Nexus One 480x800 AVD
<img src="https://user-images.githubusercontent.com/197044/116462964-6508b000-a86a-11eb-971e-66b58c32dc21.gif" width="25%">

2021-04-28 20:53 UTC, walczakkamil commented
> @suside and @walczakkamil Your approval does not result in merging this PR sooner. We need a critical and careful review of the code and not just "looks" good or "ready to merge".
> Or more specific: only core developers should be able to approve PRs. But this is not configured (protected branches), currently.

Hi,
I understand.
I have looked at the source code and it doesn't look like there are any bugs.  I appreciate the contribution to the work on the project, but I would also like to draw attention to the need for this change.  It is simple and should not affect the rest of the application and can make life easier for many people.
Br
Kamil

2021-04-28 21:31 UTC, tolot27 commented
Just to summarize the discussion and to list points to review and (potentially) solve:

- [ ] smaller display size https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-664024196
- [ ] concerns about "multi purpose insulins" like NPH
- [ ] pure long-acting/basal insulins
- [ ] correctness of activity profiles

Three new long acting insulins (Levemir, Basaglar and Tresiba) are added with this PR and a new term "ultra-long acting" (means a duration of nearly a day or longer) was introduced.
The profiles of Lantus, Toujeo and NovoRapid were corrected, but I could not find any changes in the NovoRapid profile. @J141 could you confirm that NovoRapid was not changed?

The following table highlights the additions and changes:
![image](https://user-images.githubusercontent.com/1370732/116475056-976dd980-a879-11eb-8adb-cfcfad6e87bb.png)

2021-04-28 22:03 UTC, tolot27 commented
If checked how xDrip determines if an insulin is basal:
https://github.com/NightscoutFoundation/xDrip/blob/38fee03be56da6ce9cbe90e08dbe8e4b651c6edc/app/src/main/java/com/eveningoutpost/dexdrip/Models/InsulinInjection.java#L37-L39
and `maxEffect` is filled with the duration:
https://github.com/NightscoutFoundation/xDrip/blob/38fee03be56da6ce9cbe90e08dbe8e4b651c6edc/app/src/main/java/com/eveningoutpost/dexdrip/insulin/LinearTrapezoidInsulin.java#L27-L30

Hence, Insulatard (NPH) will be treated as a basal insulin, completely, if and only if "Use Basal Activity" is checked. The same applies to the already existing long acting insulins Lantus and Toujeo.

The same would apply to the newly added long acting insulins Levemir, Basalglar and Tresiba. Hence, the discussion about correct prediction of NPH and basal insulins is valid and very important, but out of scope of this PR.

2021-04-28 22:25 UTC, tolot27 commented
Regarding correctness of the activity profiles I recommend to check only peer-reviewed publications or FDA and EMA studies and reports. I know that they are not always valid (e.g. because of small sample size), but IMHO the best starting point.

As J141 already found:

[Ultra-long-acting insulins: A review of efficacy, safety, and implications for practice](https://alliedhealth.ceconnection.com/ovidfiles/01741002-201807000-00005.pdf)
[NovoRapid: Assessment report for paediatric studies submitted according to Article 46 of the Regulation (EC) No 1901/2006](https://www.ema.europa.eu/en/documents/variation-report/novorapid-h-c-258-p46-0044-epar-assessment-report_en.pdf)
[Toujeo® vs Lantus® (insulin glargine injection) 100 Units/mL: PK/PD and pivotal data](https://www.toujeopro.com/clinical-overview/toujeo-vs-lantus)
[AFREZZA® Prescribing Information](https://www.afrezza.com/pdf/Prescribinginfo.pdf)

@J141 Also, I recommend to provide a reference which was used to get insulin profile values.

2021-04-28 22:29 UTC, tolot27 commented
> > @suside and @walczakkamil Your approval does not result in merging this PR sooner. We need a critical and careful review of the code and not just "looks" good or "ready to merge".
> 
> The thing is that there is **no code to review here**, only updated insulin list and small gui change, which you can see on screenshots.
> And if by _critical and careful review of the code_ you mean basal issues this [#1388 (comment)](https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-664859627) of the PR author pretty much sums it up.

Do you see what I mean with a "critical and careful review"? With "code" I meant all changes of the PR, including the insulin profiles encoded using JSON.

2021-04-28 22:31 UTC, tolot27 requested changes
I've created a list of points to address. After providing the source of the new insulin profiles, I'll review it again.

2021-04-28 22:33 UTC, tolot27 commented on app/src/main/res/layout/activity_insulinprofile_editor.xml
> +                    android:layout_gravity="bottom"
Please try to reproduce what is posted by @gruoner in https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-664024196

2021-04-29 05:35 UTC, kresimirjedud commented
Hi all,

just a short notice from me:

1. I can't see *Humalog junior* on your insulin list. I know it's probably
the same as Humalog, but anyway...

2. there will always be new insulins on the market. Perhaps the list
shouldn't be hardcoded (predefind). Perhaps there should be a possibility
to add new ones by user itself.

Probably you already discussed this earlier so just ignore point 2, but pls
consider point 1.

Regards,
KJ

sri, 28. tra 2021. 23:31 Mathias Walter ***@***.***> je
napisao:

> Just to summarize the discussion and to list points to review and
> (potentially) solve:
>
>    - smaller display size #1388 (comment)
>    <https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-664024196>
>    - concerns about "multi purpose insulins" like NPH
>    - pure long-acting/basal insulins
>    - correctness of activity profiles
>
> Three new long acting insulins (Levemir, Basaglar and Tresiba) are added
> with this PR and a new term "ultra-long acting" (means a duration of nearly
> a day or longer) was introduced.
> The profiles of Lantus, Toujeo and NovoRapid were corrected, but I could
> not find any changes in the NovoRapid profile. @J141
> <https://github.com/J141> could you confirm that NovoRapid was not
> changed?
>
> The following table highlights the additions and changes:
> [image: image]
> <https://user-images.githubusercontent.com/1370732/116475056-976dd980-a879-11eb-8adb-cfcfad6e87bb.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-828793317>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARCE57T4HXCB6LKYYEXUNP3TLB5DVANCNFSM4PGDK7JQ>
> .
>

2021-05-05 06:34 UTC, suside approved these changes
> - [ ] correctness of activity profiles

Please understand that currently users have to pick completely different profiles, FIASP instead Apidra for example. So even if @J141 profiles are somehow not 100% correct - this is still better situation than what is now on master branch.

2021-05-05 09:27 UTC, tolot27 commented
> 1. I can't see *Humalog junior* on your insulin list. I know it's probably the same as Humalog, but anyway...

There is no "anyway". "Humalog junior" is not the full name. It is called "Humalog Junior KwikPen" and indicates an insulin pen, not an insulin. This pen contains Humalog 100IE/ml. The advantage is that one can inject in 0.5 steps instead 1.0. Hence no new insulin.

> 2. there will always be new insulins on the market. Perhaps the list shouldn't be hardcoded (predefind). Perhaps there should be a possibility to add new ones by user itself.

That's unlikely to be happen because only reviewed insulin types will be added in the future.

2021-05-05 20:31 UTC, tolot27 commented
@suside 
> I would gladly fix this but I have no access

As shown below all comments: "Add more commits by pushing to the [master](https://github.com/J141/xDrip) branch on [J141/xDrip](https://github.com/J141/xDrip)."

You can also read [Committing changes to a pull request branch created from a fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork).

2021-05-05 21:46 UTC, ckidow commented on app/src/main/res/raw/insulin_profiles.txt
> +    "profiles":
I've created this [pull request](https://github.com/J141/xDrip/pull/1) from a fork of the J141 / xDrip fork ... maybe someone got access to merge this?

2021-05-05 22:04 UTC, tolot27 commented on app/src/main/res/raw/insulin_profiles.txt
> +    "profiles":
I've fixed this in place. @ckidow It does not work that way. You had to push to J141 master to get your changes automatically appear in the PR.

2021-05-05 22:11 UTC, tolot27 commented
The most important part is to review the new insulin profiles and provide references.

2021-05-05 22:46 UTC, tolot27 commented
The first insulin is not fully shown (can be seen in @suside comment https://github.com/NightscoutFoundation/xDrip/pull/1388#discussion_r622484197 as well):
![Screenshot_1620254295](https://user-images.githubusercontent.com/1370732/117218447-73734080-ae03-11eb-9782-c652a6dc56dc.png)![Screenshot_1620254658](https://user-images.githubusercontent.com/1370732/117218827-36f41480-ae04-11eb-9b10-a9f12a8b3e16.png)
The drop downs also have a different sorting than the checkboxes:

The English text should be adjusted as well. It is noted that "at least one, max three profiles" can/should be enabled, but all profiles are enabled per default and there is no constraint enforcement that checks the number of checked profiles.

Conclusion: A rework of the UI is highly recommend.

2021-06-03 14:21 UTC, TheConen commented
Is there any timeline on when this is coming into master? I'm currently using Apidra and Toujeo and eagerly waiting for this - or is there a nightly build that I can install while waiting for it to come to master?

2021-06-08 16:51 UTC, TheConen commented
In case anyone else doesn't want to wait (#WeAreNotWaiting) here is an APK that includes this PR: 
[xdrip-pr1388.zip](https://github.com/NightscoutFoundation/xDrip/files/6618339/xdrip-pr1388.zip)

2021-06-12 11:26 UTC, RolihlahlaD commented
> In case anyone else doesn't want to wait (#WeAreNotWaiting) here is an APK that includes this PR:
> [xdrip-pr1388.zip](https://github.com/NightscoutFoundation/xDrip/files/6618339/xdrip-pr1388.zip)

I cannot get the apk in this zip file to instal on my Android phone. 

My phone recognises that it hasn't come from the play store. I ask my phone to install it anyway, but it won't install.

If anyone can tell me why it won't install I shall be most grateful.

If there is going to be an official release of this pull request it would be very much appreciated if it could be released as soon as possible. I note the various discussions about the challenges of adding other long acting insulin, but factually there are currently long acting insulins included, so it makes no sense (to me at least) not to include the newer long acting insulin already available which people are using.

Everyone using this shod be aware that the projections shown are a rough guide only and should not be relying on it to make specific treatment decisions.

2021-06-27 15:40 UTC, fedemotta commented
I am also waiting for this PR. Can I help in any way (Testing, Bug fixing, etc)?

2021-07-16 18:16 UTC, J141 commented
Considering we've gone 13 months without any movement, repeated off-track discussions going completely out of scope of this PR, requests for sources which are right in the PR's description, and updates to the PR's source code which then expand the scope leading to yet more discussion, I think this PR is going nowhere. I've long since moved on with a forked and experimental version of xDrip so have little motivation to keep this (endless) discussion going.

If anyone would like to take up the banner and try to actually get this change included, please do. I will delete my public fork of xDrip on August 1st, 2021 so forking j141/xDrip is recommended.

2021-07-16 21:37 UTC, Texnosochi commented
> > In case anyone else doesn't want to wait (#WeAreNotWaiting) here is an APK that includes this PR:
> > [xdrip-pr1388.zip](https://github.com/NightscoutFoundation/xDrip/files/6618339/xdrip-pr1388.zip)
> 
> I cannot get the apk in this zip file to instal on my Android phone.
> 
> My phone recognises that it hasn't come from the play store. I ask my phone to install it anyway, but it won't install.
> 
> If anyone can tell me why it won't install I shall be most grateful.
> 
> If there is going to be an official release of this pull request it would be very much appreciated if it could be released as soon as possible. I note the various discussions about the challenges of adding other long acting insulin, but factually there are currently long acting insulins included, so it makes no sense (to me at least) not to include the newer long acting insulin already available which people are using.
> 
> Everyone using this shod be aware that the projections shown are a rough guide only and should not be relying on it to make specific treatment decisions.

If you remove your own and install after unpacking the ZIP Everything works. I already know for sure that the insulin lists are all marked, this can cause a problem for many because of the choice of three positions.

2021-07-17 22:54 UTC, tolot27 commented
> If anyone would like to take up the banner and try to actually get this change included, please do. I will delete my public fork of xDrip on August 1st, 2021 so forking j141/xDrip is recommended.

@J141 Please give me some more month. I'm working on this issue and hope to get it soon ready for approval. If you delete your fork, we will lose all the discussion here.

@fedemotta Yes, you can help. Please see the task list in https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-828793317

2021-07-18 23:19 UTC, Texnosochi commented
> Если кто-то еще не хочет ждать (#WeAreNotWaiting), вот APK, который включает этот PR:
> [xdrip-pr1388.zip](https://github.com/NightscoutFoundation/xDrip/files/6618339/xdrip-pr1388.zip)

I saw the application and immediately want to inform you - the widgets do not work (redmi 9); mini bubble connects, but does not accept data; libra2 patch app also does not accept data.

2021-07-18 23:21 UTC, Texnosochi commented
> > If anyone would like to take up the banner and try to actually get this change included, please do. I will delete my public fork of xDrip on August 1st, 2021 so forking j141/xDrip is recommended.
> 
> @J141 Please give me some more month. I'm working on this issue and hope to get it soon ready for approval. If you delete your fork, we will lose all the discussion here.
> 
> @fedemotta Yes, you can help. Please see the task list in [#1388 (comment)](https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-828793317)

I can help with checking the application. If you need it.

2021-07-19 04:26 UTC, tolot27 commented
Please discuss apk related stuff elsewhere. That is off-topic.

2021-07-21 13:21 UTC, J141 commented
> 
> 
> > If anyone would like to take up the banner and try to actually get this change included, please do. I will delete my public fork of xDrip on August 1st, 2021 so forking j141/xDrip is recommended.
> 
> @J141 Please give me some more month. I'm working on this issue and hope to get it soon ready for approval. If you delete your fork, we will lose all the discussion here.
> 
> @fedemotta Yes, you can help. Please see the task list in [#1388 (comment)](https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-828793317)

I'll leave the PR in for now.

2022-01-30 12:28 UTC, suside commented
So I re-opened [this PR on my fork](https://github.com/suside/xDrip/pull/4), it builds APK on each commit, you can [download ready to install xDrip app](https://github.com/suside/xDrip/suites/5111504177/artifacts/153259384) from Artifacts sections of GH Action run.
If you have any questions or comments please post them there.

2022-01-31 20:42 UTC, tolot27 commented
@suside Please let us work together on https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-828793317 instead of just creating an apk elsewhere.

2022-01-31 20:43 UTC, tolot27 commented
@J141 Can't you unsubscribe from this PR, can you? If yes, I like to reopen it.

2022-02-04 17:07 UTC, suside commented
> @suside Please let us work together on [#1388 (comment)](https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-828793317) instead of just creating an apk elsewhere.

I'm really into working together @tolot27 :wink: but:

- I am unable to create peer-reviewed publications etc. regarding insulin profiles myself.
- What could be found on the internet was already provided.

Therefore (and I said this last year) I see no other option than just use it as it is. However, if you have something specific in mind just let me know!

2022-03-27 16:47 UTC, aurixtech commented
Any update on merging this PR? It would be useful to have, even if only from a logging standpoint. When sharing xDrip via Nightscout the "caregiver" can then verify that both bolus and basal treatments have been administered. Plus, it would be nice to have Apidra as an option for selection. Making a treatment note and having no option to select the correct insulin type is problematic when the treatment needs to be reviewed by a caregiver/medical professional.

Much thanks for the works so far!

2022-03-28 08:21 UTC, J141 commented
@aurixtech Sadly, the PR has reached a dead end for now. 

@tolot27 wants proof that the insulin profiles are correct, but the available info for each type of insulin and their activity profiles has already been provided in the original description of the PR. Besides the research done and papers available on that which have already been linked, We can't exactly do peer-reviewed research ourselves.

If you have anything in mind on how to proceed @tolot27 I'd love to hear it. As suside has said, what info is available has already been linked, and we don't exactly have accesss to the required equipment to do peer-reviewed research ourselves. I'd love to hear if you have a path forward in mind or if the PR should actually be closed.

2022-04-29 15:54 UTC, jamorham commented
I would like to split this PR to get at least some goodness out of it and provide utility to users. In my opinion there is no accurate information about insulin profiles, none of the manufacturer curves I have seen really seem to match with personal reality and there may also be significant variations even between individuals.

The data in the insulin profiles is intended as a reference guide, its good if its as close as we can get to good data but its not absolutely essential.

I would like to split this in to 3 parts and am happy to take guidance on the best way to achieve this:

1) Add insulins that are not currently supported. Even if these profiles are not 1000% accurate it is better than not having them as is the current situation.
2) If the UI elements are problematic due to too many items then that can be improved. If point 1 requires point 2 then I guess this needs to happen at the same time.
3) Change/correct existing profiles if a consensus can be achieved as to a better set of numbers for those curves.

2023-01-22 00:52 UTC, tedo78 approved these changes

2023-03-09 15:15 UTC, AlFontal commented
So... What's the status on this? Is there any way to have a Novopen 6 assigned to Tresiba?

2023-03-10 21:35 UTC, yevhenlisovenko commented
Also looking the changes in master as well. It will be very helpfull to see my insulin profile in xDrip.

2023-09-19 22:42 UTC, TheConen commented
Can we please finally merge this? This PR has been open for over 3 years, I am still using a version of xDrip+ that I built myself out of this PR about 2 years ago because I am using Apidra and Toujeo. I would like to be able to update my xDrip+. 

From a user standpoint I can say: I don't care about any activity curves. I know that Apidra lasts about 2hrs for me - I don't need xDrip+ to tell me that. What I do need is to be able to choose the Insulin type I actually use when entering treatments so I have a proper documentation.

2023-10-04 17:51 UTC, mateusglucas commented
I was just searching how to choose Tresiba on xDrip+ and ended finding the Pandora's box. I think no one cares about the activity curves. It is only a mean activity, which doesn't exactly apply to anyone. It helps, but in practice no one takes the activity curves for granted to the degree of precision being discussed here.

Why not only merge the new profiles, without modifying the already defined activity curves?

2023-10-19 04:40 UTC, AlanRobertClark commented
Fully agree with @mateusglucas: Please add Apidra profiles to the existing activity curves!

2023-10-26 20:27 UTC, TheConen commented
Since this PR seems to be dead, I resolved the merge conflicts and created #3157 .
Also, for those that cannot wait, I created an APK up-to-date with the current master.
Keep in mind that this uses different signatures than the official xDrip+ app, so you will have to uninstall xDrip+ to install this one.

[xdrip-pr1388-20231026.zip](https://github.com/NightscoutFoundation/xDrip/files/13182615/xdrip-pr1388-20231026.zip)

2023-11-08 20:48 UTC, TheConen commented
Since #3157 has been merged, I think this PR can be closed now.

2023-11-10 20:13 UTC, jordy-de-koning commented
> Since #3157 has been merged, I think this PR can be closed now.

I agree. This PR is now closed.

2023-11-10 20:13 UTC, closed without merging