Add a new command 0x08
NightscoutFoundation/xDrip pull request #1405
Opened 2020-08-16 03:22 UTC by bubbledevteam

Add a new command 0x08(implemented in Bubble FW v2.6 and upper) which request decrypted Libre2/Pro/US 14days raw data from Bubble, the data Structure is the same as Libre1,make xdrip+ algorithm work with all Libre type sensors.

2020-09-02 14:04 UTC, jamorham commented
Hi thanks for this. There seem to be quite a few changes in the diff. Are there any unrelated changes to those that have already been described included in this pr?

2020-09-03 10:39 UTC, tzachi-dar commented
Generally speaking, this PR does a few things that can be categorized as:
1) Allow bubble to decrypt libre2 data and send it to xDrip as libre1 data.
2) Some general changes to the code.

Right now I'm working on a similar pr that will allow all devices to work on libre2 data (https://github.com/NightscoutFoundation/xDrip/pull/1429).

So, I think that it would be better if this PR will be limited to the changes in the bubble code only.
On the HandleGoodReading a new parameter was added: decripted_data 

If the bubble fw has already decrypted the code, they can simply mark this data as decrypted, and all should just work.

2020-11-09 06:05 UTC, tolot27 commented
Does this PR requires #1396? If yes, can they be merged?

2020-12-16 09:04 UTC, jamorham commented
What is the current state of this PR, is the command supported elsewhere already? Can it be cleaned up to just include the changes needed? thanks

2021-02-14 17:47 UTC, parapenT1sta commented
@tolot27 and @jamorham Do you think this can be merge? This will be usefull for users using Bubble and not requiring OOP2 to be installed.

2021-02-14 17:48 UTC, parapenT1sta commented
@jamorham I think this command is also used on Diabox.

2021-02-16 17:52 UTC, parapenT1sta commented
@jamorham https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/BluetoothTransmitter/CGM/Libre/Bubble/CGMBubbleTransmitter.swift#L164

2021-02-16 22:56 UTC, tolot27 commented
@bubbledevteam Please can you resolve the merge conflicts and limit the changes to the bubble code only?

2021-02-18 15:18 UTC, tzachi-dar requested changes
I have read this pr again after oop2 code is already working.

This change (with the modifications asked) should allow people to use libre2 without oop2.

This will be super helpful for people with watches that are not supported by oop2.

2021-02-24 05:24 UTC, bubbledevteam commented on app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/LibreUtils.java
> +        byte[] patchInfo = PersistentStore.getBytes("patchInfo");
this is for distinguishing the sensor type, I tested the previous codes ,the sensor type is not right displayed in xdrip+.

And this is for Bubble only as I code it if the patchInfo is null, just make it Libre as default

2021-02-24 05:26 UTC, bubbledevteam commented on app/src/main/java/com/eveningoutpost/dexdrip/LibreAlarmReceiver.java
> +                                if ("Diabox".equals(from)) {
I  am sorry to submit this part ,in fact it is for this https://github.com/NightscoutFoundation/xDrip/pull/1395

2021-03-01 10:01 UTC, closed without merging