Dspnikder battery info rx message
NightscoutFoundation/xDrip pull request #1595
Opened 2021-01-07 11:02 UTC by dspnikder

Well, this one happily passes through travis (in only 16:25 seconds which is...... a lot.  Better alternatives? Faster alternatives? Commercial is fine by me, I'd sponsor it although I think pretty much everyone would give this project free access - or close to it)

Well... I think I might start with just writing some tests for all the messages in Ob1. Or something.

2021-01-08 01:20 UTC, tolot27 requested changes
Thanks for keeping on the battery issue.

Just a few comments (I did not test it yet).

- I cannot find a reference to the newly added Log.java. Is this class required?
- Please use a consistent code format. I know, currently we do not have well defined rules.
- Please review grammar in comments and strings (i. e. "Malformed BattteryInfoRxMessage")
  - I would call it "New/unknown" instead of "Malformed".

2021-01-10 08:24 UTC, dspnikder commented
Log is in the test package under
android.util.Log

When writing unit tests you mock the Log and normally the standard included Log mock is enough, however we are using some additional methods (wtf() which is sort of what I thought too) which meant I needed to patch the existing mock and place it in our test/src.

2021-01-11 21:41 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/G5Model/BatteryInfoRxMessage.java
> +     * Surprisingly enough toString is one of those methods you s
This sentence is incomplete.

2021-01-11 21:42 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/G5Model/BatteryInfoRxMessage.java
> +     * Predicate replacement for brevity in constructur.
constructor

2021-01-11 21:44 UTC, tolot27 commented on .gitignore
> +gradle/wrapper/dists
Which build environment do you use? I've never seen these directories and wonder why they are created.

2021-01-11 21:54 UTC, tolot27 commented on app/src/test/java/com/eveningoutpost/dexdrip/G5Model/BatteryInfoRXTests.java
> + * for the values in voltageA/B/resistance, temprature and
temperature

2021-01-11 22:13 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/G5Model/BatteryInfoRxMessage.java
> +                        UserError.Log.e(TAG, "Unknown BattteryInfoRxMessage packet opcode: 0x" + Integer.toHexString(bytes[0]) + " and length was " + bytes.length + ", expected is 10 or 12");
Typo: BatteryInfoRxMessage

2021-01-11 22:16 UTC, tolot27 commented on app/src/test/java/com/eveningoutpost/dexdrip/G5Model/BatteryInfoRXTests.java
> +public class BatteryInfoRXTests {
A unit test for a class is typically named with the class name and the suffix "Test"; in this case: `BatteryInfoRxMessageTest`.

2021-01-11 22:19 UTC, tolot27 requested changes
Thanks a lot for this PR and the detailed code documentation.

Please can you also add a test for the `PacketValidator` class and the overwritten function `toString`. This will increase the test coverage to nearly 100%.

2021-01-11 22:20 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/G5Model/BatteryInfoRxMessage.java
> +     * an illegalArguemntException.
`IllegalArgumentException`

2021-01-11 22:31 UTC, tolot27 commented
You did a good job with the documentation. A further great step would be to document it using [JavaDoc](https://www.oracle.com/de/technical-resources/articles/java/javadoc-tool.html) syntax and in such a way that generated docs are a good source of information.

Please also [reformat the code](https://stackoverflow.com/a/16580200/10373188) for a consisting (default) code style.

2021-01-11 22:41 UTC, tolot27 commented
> Log is in the test package under
> android.util.Log
> 
> When writing unit tests you mock the Log and normally the standard included Log mock is enough, however we are using some additional methods (wtf() which is sort of what I thought too) which meant I needed to patch the existing mock and place it in our test/src.

Still, I do not see the file in use. Is it somehow injected? Code coverage of this file is zero.

2021-01-13 08:41 UTC, tolot27 commented
@dspnikder Please provide a separate PR for the UserError "case" and a detailed explanation why it is necessary to change its implementation.
Mixing solutions for different issues into one PR makes it unlikely that such PR gets ever merged.

2021-01-13 09:45 UTC, dspnikder commented
> @dspnikder Please provide a separate PR for the UserError "case" and a detailed explanation why it is necessary to change its implementation.
> Mixing solutions for different issues into one PR makes it unlikely that such PR gets ever merged.

Then so be it.  Feel free to close it.

2021-01-13 23:03 UTC, tolot27 commented
> Then so be it. Feel free to close it.

I don't want to close this PR because I believe it is an important one. Please just hard reset the branch to commit eb1e2d8. Before doing it, create a new branch based on upstream/master and cherry pick 0ab2c134. This commit should be provided with a different PR, anyway.

It is also important to resolve merge conflicts and not committing them as you did with 8d64253 (file `.gitignore`).

I also recommend to use `git rebase upstream/master` instead of `git merge upstream/master`. This gives a much cleaner history.

2025-04-11 23:58 UTC, closed without merging