Libre2 sync raw
NightscoutFoundation/xDrip pull request #1686
Opened 2021-03-28 23:10 UTC by jordipbou

Adds synchronization of Libre2 raw values with xDrip+ Sync service. 

No options added as it uses Less Common Settings > Advanced settings for Libre 2 < show Raw values in Graph to decide if sync raw values (on master) and to show them on follower.

For implementing it a new message type has been added "l2r" to xDrip+ sync sender and receiver.

2021-04-05 09:51 UTC, mukich approved these changes

2021-05-03 12:57 UTC, Estetne approved these changes

2021-05-03 18:37 UTC, tolot27 commented
@tzachi-dar Does the OOP2 enable raw data sync? As far as I know, this is out of scope of OOP2.

2021-05-03 18:40 UTC, tolot27 commented
@mukich and @Estetne Please do not approve pull requests until you did a careful review. We have the same discussion several times. Please have look at https://github.com/NightscoutFoundation/xDrip/pull/1388#issuecomment-828700145 and the following discussion and review to get an insight what is meant be a "careful review".

2021-10-05 05:24 UTC, tolot27 requested changes
The implementation looks good so far. Please address the code formatting comments.

How well is it tested?

@tzachi-dar Please can you review this PR as well?

2021-10-05 05:24 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/GcmListenerSvc.java
> +                    Libre2RawValue currentRawValue = Libre2RawValue.fromJSON (payload);
Please use consistent code formatting (no spaces before bracket of function parameter list), at least for the code you have changed.

2021-10-05 05:24 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/LibreReceiver.java
> +                                    GcmActivity.syncLibre2RawReading (currentRawValue);
Please use consistent code formatting (no spaces before bracket of function parameter list), at least for the code you have changed.

2021-10-05 05:24 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/Models/Libre2RawValue.java
> +        import android.util.Log;
Please apply code formatting to the whole file.

2021-11-29 18:18 UTC, jordipbou commented
As requested, format has been updated.

About testing, we use this implementation daily to monitor our daughter glucose values remotely. No issues so far.

2021-12-18 13:48 UTC, infossk commented
We have been using our own build with this functionality for more than a month and there are no problems with it.  I would be happy to be merged.

2021-12-18 18:44 UTC, Estetne commented
We use it for about 3 months and everything is ok

2021-12-21 06:16 UTC, tolot27 commented
@jordipbou Please resolve the merge conflict.

2021-12-21 06:26 UTC, tolot27 commented
> As requested, format has been updated.

Thanks for the update. In the future, please create one commit containing the changes instead of individual commits per file.

2021-12-21 08:38 UTC, jordipbou commented
@tolot27 Merge conflict has been resolved.

2022-01-03 12:29 UTC, tolot27 approved these changes

2022-01-03 12:45 UTC, tolot27 requested changes
Please add unit tests were possible. We have to increase code coverage by careful testing of the implemented methods. Currently, we are at only 5% code coverage. See https://app.codecov.io/gh/tolot27/xDrip for details.

2022-01-03 12:45 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BgGraphBuilder.java
> +            || (DexCollectionType.getDexCollectionType () == DexCollectionType.Follower && prefs.getBoolean("Libre2_showRawGraph",false)))
Still two minor code formatting changes from previous to your commit. Please insert a space before `false` in `prefs.getBoolean("Libre2_showRawGraph",false)` at line 215 and 1323.

2022-01-03 12:45 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/Models/Libre2RawValue.java
> +    public String toJSON() {
Please add a unit test for at least these two functions of `Libre2RawValue`.

2022-11-10 14:01 UTC, twinko commented
is it possible to push this further?

2024-07-28 17:01 UTC, closed without merging