Capitalze "Disable alert" on the alert edit screen
NightscoutFoundation/xDrip pull request #1788
Opened 2021-07-22 05:27 UTC by eheydrick

Be consistent about capitalizing the first word on the alert edit screen.

2021-07-31 22:25 UTC, tolot27 requested changes

2021-11-18 23:09 UTC, tolot27 commented on app/src/main/res/values/strings.xml
> +    <string name="disable_alert">Disable alert</string>
I've updated the remaining alert strings as well.

2021-11-18 23:10 UTC, tolot27 approved these changes

2021-11-18 23:11 UTC, tolot27 commented
I've changed the Crowdin settings some time ago to not remove changed strings. The translated string just need a re-approval. This can't be avoided for tiny changes such as capitalization or punctuation.

2021-11-19 00:03 UTC, eheydrick commented
Thank you @tolot27.

2022-01-03 11:56 UTC, jamorham approved these changes

2022-01-04 09:46 UTC, merged