Carb entry error
NightscoutFoundation/xDrip pull request #1808
Opened 2021-08-11 03:53 UTC by Navid200

**Please don't merge yet!**
This may be a mistake.  Please see side effects and tests below.

**Why do we need this**
When entering carb values, if the user enters 3 decimal points, what is entered is an integer value equal to the last two digits of the fractional part of the number.  For example, if the user enters 1.298, what will be entered is 98, which is a significant error.

Fixes https://github.com/NightscoutFoundation/xDrip/issues/565

**Is there a workaround?**
The user can avoid entering more than 2 decimal points.

**Are there any side effects?**
I don't know.  I need your help.  Is it possible that the line I have commented out  was needed for older versions of Android?
Is there any other keypad (other than treatment) that needs the line that I have commented out?

**Tests**
I have only tested this with one Android 8 device.
I am the worst person for testing this because I never use the treatment menu.
How can I test this?
How can I make sure that no other keypad is screwed up by this change?

2021-08-11 12:52 UTC, Navid200 commented
Why would the user enter "Blood 3.622 grams"?  Regardless of if they are using speech or not.
Perhaps, originally the menu allowed such an entry.
But right now, the user has to first select blood or carbs or insulin; then, enter a value.
After all the entries are entered, xDrip combines then with space between.

I don't understand the need for this splitting.   Unless this applies to a different keypad that has to do with simulation or some other function that I have never used.

Is there any entry in xDrip that accepts blood and carbs entered in one shot by the user?  If not, I don't see the need for this splitting.

2021-08-13 06:13 UTC, tolot27 requested changes
Entering values manually using the keypad is totally different from speech input. If you use voice control you would not speak extra voice commands to switch between the different treatment input pages. You just say: "blood 3.6 and 10 carbs and 2 insulin units" or something like that.
The speech-to-text processing is completely separated from manual input.
To resolve #565, just the manual input route should be fixed and not the speech processing. Sometimes, the speech recognition returns strange text which is filtered/adapted by the function `naturalLanguageRecognition` you have changed.

2021-08-13 13:44 UTC, Navid200 commented
There is only one route.  The splitting should only be applied to speech input.  But, it also is applied to text entry resulting in the reported bug.

After 1.234 is split into two entries of 1.2 and  34, the damage is done.  
I can place a conditional before this and for carb entry only convert that to 1 as the carbs should be entered as integer anyway.
But, what happens if someone adds another speech command tomorrow that requires another manipulation added, which screws up text entry again?

The best solution, in my opinion, is to only have speech go through naturalLanguageRecognition, but, not text from the keypad.  Currently, keypad entries also go through it.

I am happy to do the work.  But, can we please wait for input from jamprham as to his preferred approach?  I will be happy to do the work.  I am absolutely not trying to avoid to do the work.  But, I'd like to do it after we get more input.

2021-08-13 15:03 UTC, Navid200 commented
The speech recognition scheme has limitations.
Someone posted on facebook claiming that when he attempted to use the speech command to clear the transmitter queue, the speech recognition typed "clear transmitter cue", which did not clear the queue.

I told them that they should long press on the microphone symbol, instead of tapping on it, so that they can enter the command using the keyboard.
In fact, all my guides instruct people to use the keyboard instead of using speech.

Now, I hope no one adds a replacement of cue with queue in xDrip.  Please don't do that.  

I admire the intent of speech input in xDrip.  But, it has serious limitations.

2021-10-21 21:14 UTC, tolot27 commented
> > To resolve #565, just the manual input route should be fixed and not the speech processing.
> 
> Would you please highlight where the "manual input route" is?

I've debugged this. Unfortunately, input using the keypad/touchscreen is also passed to the voice input processing. I'm not particularly happy about that.

2021-10-21 21:23 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/Home.java
> -        allWords = allWords.replaceAll("([0-9]\\.[0-9])([0-9][0-9])", "$1 $2"); // fix multi number order like blood 3.622 grams
Commenting this line out removes the implemented fix. It looks like sometimes people speak two voice treatment commands right after another, maybe in different word/number ordering like "blood 3.6" followed by "22 grams". The voice recognition engine concatenates the recognized text to a single string without a separator between the two commands.
The regex tries to fix this but is incomplete. Here is an improved regex: `([a-zA-Z]+ \d{1,3}(?:\.\d)*)(\d+(?:\.\d)* [a-zA-Z]+)`. This handles the following cases correctly:
```
blood 3.622 grams
grams 223.6 blood
grams 1802.9 blood
grams 180114 blood
1.298 carbs
```

They will be changed to:
```
blood 3.6 22 grams
grams 22 3.6 blood
grams 180 2.9 blood
grams 180 114 blood
1.298 carbs
```

Now, there is a separator between the numbers but only if the input string starts with a word and ends with a word. The latest example is unaffected.

All examples will be processed correctly with this regex.

2021-10-21 21:23 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/Home.java
> -        allWords = allWords.replaceAll("([0-9]\\.[0-9])([0-9][0-9])", "$1 $2"); // fix multi number order like blood 3.622 grams
Commenting this line out removes the implemented fix. It looks like sometimes people speak two voice treatment commands right after another, maybe in different word/number ordering like "blood 3.6" followed by "22 grams". The voice recognition engine concatenates the recognized text to a single string without a separator between the two commands.
The regex tries to fix this but is incomplete. Here is an improved regex: `([a-zA-Z]+ \d{1,3}(?:\.\d)*)(\d+(?:\.\d)* [a-zA-Z]+)`. This handles the following cases correctly:
```
blood 3.622 grams
grams 223.6 blood
grams 1802.9 blood
grams 180114 blood
1.298 carbs
```

They will be changed to:
```
blood 3.6 22 grams
grams 22 3.6 blood
grams 180 2.9 blood
grams 180 114 blood
1.298 carbs
```

Now, there is a separator between the numbers but only if the input string starts with a word and ends with a word. The latest example is unaffected.

All examples will be processed correctly with this regex.

2021-10-21 21:57 UTC, Navid200 commented
@tolot27 Are you saying I replace 
("([0-9]\\.[0-9])([0-9][0-9])", "$1 $2")
with
([a-zA-Z]+ \d{1,3}(?:\.\d)*)(\d+(?:\.\d)* [a-zA-Z]+)
on line 1362?

2021-10-22 04:57 UTC, tolot27 commented
BTW: We should consider implementing a unit test for the voice command fix. But this requires separating the multiple regex from the remaining function code.

2022-06-25 18:42 UTC, tolot27 commented
@Navid200 I dug into it more and this PR indeed solves a bug in xDrip - even if we are not happy about the common handling of manual and language input by the natural language processing code and even if language recognition is not perfect.

> I don't believe we should be telling people how much insulin to take.

We don't do that. We just improve the code to handle the input. The processed values should match as close to the input as possible.

> Even more so if they are visually impaired such that they need to use voice to tell xDrip how much they have eaten.

That's way it is important to fix the processing because otherwise such people does not have any chance to get their voice input processed correctly.

Hence, please open this PR again and add the [comment](https://github.com/NightscoutFoundation/xDrip/pull/1808#discussion_r735097769), otherwise I'll open a new PR.

2023-01-26 05:30 UTC, closed without merging