Bugfix: Wear complication null with Share and Nightscout follow sources
NightscoutFoundation/xDrip pull request #1846
Opened 2021-10-08 19:06 UTC by JasonJShuler

Fix for issue #303 - confirmed fixed using Follow Share source.

1. Updated Listener service on WearOS to apply the calibration-ignoring logic previously exclusive to Dexcom Native, to now include Dexcom Share Follow. This is appropriate as Follow BG values are identical to Native values and do not require calibration. Credit to @gregorybel for finding this one!
2. Populating the BgReading uuid in the ShareFollow and NightscoutFollow source entry processors

The null uuid in the BgReading values created by the follow sources were causing a nulPointerException in BgReading.getByUuid(). This was causing BgReading.last() to always return null.
The most visible consequence was the complication provider always getting null values, however BgReading.last() is used extensively throughout the Wear OS side code (one example is in checking to see if it needs to perform an update - without the uuid, the answer was always yes)

These are the only instances in the app-side code of "new BgReading" (outside of the BgReading class itself) that do not populate the uuid. The same method is used here as in the Native Dex source.

Confirmed working on Wear OS emulator and Galaxy Watch 4.

NOTE: If it was intended that the uuid be null, a condition to check for a null parameter can be added to getByUuid(). (This is what I did first, but it felt like a hack given my limited understanding of the codebase)

![Demo_Follow_Complication_Working](https://user-images.githubusercontent.com/29778397/136631843-e99389fa-a2ad-42d5-b302-ec5ae04b359f.png)

2021-10-09 07:20 UTC, FreDiabetics commented
Does this work for dexcom readings recieved by the local broadcast? datasource 640G/Eversense? as I'm using the build-your-own-dexcom-app to recieve my bg and push it to xDrip+ via AndroidAPS.

2021-10-12 13:54 UTC, Navid200 commented
@JasonJShuler No, that's not what I meant at all.
I thought you wanted to make some changes to it.  I am not talking about the question whether to edit the existing PR or closing it and opening a new PR.  I am not talking about that question.
But, that question gave me the impression that you needed to make a change.

If you are happy with your PR as is and if it is merged, you will be happy with it and you will not need to open another PR to correct any errors in it, then leave it be.

On the other hand, if there is anything in it that you need to change, please change this to a draft.  Otherwise, it may be merged as is.  

When you say this is ready for a review, I hope you mean you are happy with this if it is merged as is.

2021-10-12 15:36 UTC, tolot27 requested changes

2021-10-12 15:36 UTC, tolot27 commented on app/src/main/java/com/eveningoutpost/dexdrip/NSClientReceiver.java
> +            //TODO: Determine impact of making this not-null - scan all code
I do not fully understand this TODO comment. Please can you explain it and maybe solve it, too?

2021-11-05 11:01 UTC, jamorham commented
Looks good to me

2021-11-06 10:49 UTC, merged

2023-06-30 14:53 UTC, andreaontheweb commented
I'm on the last nightly build 20230503 but I have still this problem. Null null on watch 5 complications, I'm a follower of a xdrip g6. Native watchface xdrip works well

2023-06-30 14:54 UTC, andreaontheweb commented
If I swap hardware source to Dexcom share it works, xdrip sync follow gives null null..