Move everything from the title to the summary
NightscoutFoundation/xDrip pull request #2076
Opened 2022-04-12 23:09 UTC by Navid200

2022-04-13 06:13 UTC, tolot27 requested changes
This is a much better solution than the previous one. Great!

`bindPreferenceTitleAppendToIntegerValueFromLogSlider` is also used for one more preference: "tidepool_window_latency" (Data Age Mins). Please can you change it there as well. Afterwards, `bindPreferenceTitleAppendToIntegerValueFromLogSlider` can be removed completely.

2022-04-13 12:35 UTC, Navid200 commented
@tolot27 
There are many more seekbars in xDrip.  I can list them all for you if you like.  The seekbar title does not wrap for any of them.

We have an instruction from @jamorham not to create large PRs.  That has always been my approach because I agree with that direction.  
If a PR improves things, please don't delay it because it does not fix everything.

I respectfully request @jamorham to approve your request before I execute it.  
I personally have no objection in editing all the xDrip seekbars.  But, if that is going to be the reason this PR will never be merged, because it is too big, I'd rather not do it in one step.

2022-04-13 13:32 UTC, tolot27 commented
> @tolot27 There are many more seekbars in xDrip. I can list them all for you if you like. The seekbar title does not wrap for any of them.

But after your PR only "tidepool_window_latency" remains which uses `bindPreferenceTitleAppendToIntegerValueFromLogSlider`. I did not request to fix all of them. I just request to modify all affecting seekbars which is just one in this case.

> We have an instruction from @jamorham not to create large PRs.

This is not a large PR and my suggestion would further reduce it. Currently, your PR duplicates code which increases maintenance efforts.

> If a PR improves things, please don't delay it because it does not fix everything.

I don't delay anything here.

2022-04-14 15:34 UTC, jamorham commented
I think this looks nicer and should solve the original issue. I haven't tested it myself. Smaller PRs are easier to merge.

2022-04-14 15:34 UTC, jamorham approved these changes

2022-04-15 10:46 UTC, merged