add Makefile
NightscoutFoundation/xDrip pull request #903
Opened 2019-06-04 22:40 UTC by afcady

This allows the project to be built in a single command (`make`).  The `Makefile` handles downloading and installing the SDKs in an essentially identical way to the `.travis.yml`, then builds with `gradle`.

However, builds with `gradle` are not fully incremental.   They appear to be much more so today than a month ago.  When I re-build with no changes, I get this:

```
BUILD SUCCESSFUL in 4m 12s
97 actionable tasks: 25 executed, 72 up-to-date
```

So 25 tasks were run unnecessary.  Of course, 72 out of 97 ain't bad, but also 4 minutes ain't good.  I was hoping I could get some assistance in making these builds properly incremental.

2019-08-03 13:33 UTC, jamorham commented
I would be surprised if you can get incremental builds working in any real sense due to the post processing done by proguard.

2019-08-03 15:18 UTC, afcady commented
Is it easy enough just to disable proguard conditionally?

2020-12-07 23:09 UTC, tolot27 requested changes
Version numbers and file names are hard-coded. Can you fetch them from the gradle build scripts?
Also, it is assumed that gradle is installed. Maybe, you should fetch it based on the `distributionUrl` in `gradle-wrapper.properties`.

Incremental compilation is mostly handled by Gradle or the Android Gradle plugin and also depends on preprocessers like annotators. Newer versions of gradle improve this. See also #1522 for further information.

2020-12-07 23:13 UTC, tolot27 commented
> Is it easy enough just to disable proguard conditionally?

Then you will loose the benefits of ProGuard. It is better to upgrade to Android Gradle plugin 3.4.0 which uses R8 to [achieve](https://developer.android.com/studio/build/shrink-code) the same tasks ProGuard addresses.

2021-01-10 19:51 UTC, afcady commented
Yeah, should be easy to do that.  Gonna look at this again soon.

2021-03-15 19:20 UTC, tolot27 commented
@afcady Please add the requested changes or delete this PR if you don't need it anymore. If you have questions, feel free to ask.

2021-04-24 13:31 UTC, Navid200 commented
@afcady Would you please update this with your plans?
Are you still interested?
Or, can we close this pull request?

Thanks

2021-05-12 11:33 UTC, Navid200 commented
Can we close this pull request please?
We can always reopen it if the developer likes to work on it again.

2021-05-12 21:33 UTC, tolot27 commented
It looks like this feature is not required anymore. Closing due to inactivity.

2021-05-12 21:33 UTC, closed without merging

2021-05-18 23:00 UTC, afcady commented
I don't know why you don't just merge the file, but I will go back and add the feature requested eventually.

2021-05-18 23:01 UTC, afcady commented
It's actually no big deal to update the file when the dependencies change, so maybe that feature is silly.  Anyway, it is no reason to block the merge or to close the request.

2021-05-19 22:11 UTC, tolot27 commented
@afcady You did not respond for a long time and we don't like to add files which we have to maintain because they contain fixed strings instead of dynamically changed variables. Currently, you are the only user which needs/likes this feature. If you like to get it merged into xDrip, please follow our suggestions, especially, if it is easy to implement it by you. Otherwise, it is unlikely that this PR will ever be merged.

2021-05-20 12:49 UTC, afcady commented
Maybe you should just merge the Makefile and then remove it if/when the fixed string ever stops working.  That is way more normal.

I can write a Makefile that can try to parse these values out of the rest of the source code.  Then we can hope that the rest of the source code won't break that crazy ouroborous code.  It makes more sense though, to just allow the fact, that every few years when you change library versions, you have to rely on someone updating those values.

It is easy to keep the fixed strings updated just by accepting of patches!

But, some day, I will write the crazy ouroborous code, maybe.  Keeping in mind, I don't use xDrip and these was just preliminary work to try to get to the point where I can work on the code enough to get it to work for me.

2021-05-20 13:18 UTC, afcady commented
Did any of the fixed strings actually change since Jun 4, 2019?

I started writing some code like this:

```
+BUILD_TOOLS_VERSION := $(shell sed -n 's/^ *- build-tools-//p' .travis.yml)
+
 GIT_DISCOVERY_ACROSS_FILESYSTEM=y
 export GIT_DISCOVERY_ACROSS_FILESYSTEM

-SDKS = "platforms;android-26" "build-tools;27.0.3" "extras;google;m2repository"
+SDKS = "platforms;android-26" "build-tools;$(BUILD_TOOLS_VERSION)" "extras;google;m2repository"
```

...and then it occurred to me.  This value has to match the `sdk-tools-linux-4333796.zip` file.  Future `sdk-tools-linux-*.zip` releases by Google will have unpredictable URLs.  So you really cannot make this work without ever having to change any strings in the future.  A feature that literally no one wants, not even you, since you don't even want the file!

Anyway I can go ahead and implement a feature that cannot ever work because no one wants that feature, since you insist on a feature no one wants before you will accept a feature only one person wants!

2021-05-20 22:08 UTC, tolot27 commented
> Keeping in mind, I don't use xDrip and these was just preliminary work to try to get to the point where I can work on the code enough to get it to work for me.

If you don't use xDrip, what is then your intention to contribute to it?

Our main goal (beside fixing bugs) is to reduce the complexity of xDrip and increase the maintainability. If we accept new code we request for unit tests which run automatically by CI and on every PR. This PR does not provide a test case, yet. If it would, it will likely fail in the future if we change the various API levels. Then we have to maintain a file which is not used by everyone, except you.

I suggest, you keep the make file in your master branch and use it on your own. There is no need to integrate it into xDrip master because xDrip builds fine and your on branches will build, too.

In my fork and local copy there are several files I'll never track, commit or push. That's not a problem.

Maybe, I've overseen the real benefit/advantage of you PR for the xDrip users or developer community. In that case, please explain it again.

2021-05-21 00:12 UTC, afcady commented
@totol27 there is no need for discussion.  I have implemented the parsing so that the fixed strings are gone.